# coding=utf-8
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bfkv.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import bfgateway_pb2 as bfgateway__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='bfkv.proto',
  package='bfkv',
  syntax='proto3',
  serialized_pb=_b('\n\nbfkv.proto\x12\x04\x62\x66kv\x1a\x0f\x62\x66gateway.proto\x1a\x19google/protobuf/any.proto2\xed\x02\n\x0b\x42\x66KvService\x12\x36\n\x04Ping\x12\x15.bfgateway.BfPingData\x1a\x15.bfgateway.BfPingData\"\x00\x12@\n\x0cPingStreamCS\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00(\x01\x30\x01\x12=\n\x0bPingStreamC\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00(\x01\x12=\n\x0bPingStreamS\x12\x14.google.protobuf.Any\x1a\x14.google.protobuf.Any\"\x00\x30\x01\x12\x31\n\x05SetKv\x12\x13.bfgateway.BfKvData\x1a\x11.bfgateway.BfVoid\"\x00\x12\x33\n\x05GetKv\x12\x13.bfgateway.BfKvData\x1a\x13.bfgateway.BfKvData\"\x00\x42$Z\"github.com/sunwangme/bfgo/api/bfkvb\x06proto3')
  ,
  dependencies=[bfgateway__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)





DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('Z\"github.com/sunwangme/bfgo/api/bfkv'))
import grpc
from grpc.beta import implementations as beta_implementations
from grpc.beta import interfaces as beta_interfaces
from grpc.framework.common import cardinality
from grpc.framework.interfaces.face import utilities as face_utilities


class BfKvServiceStub(object):
  """============================



  Kv服务

  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Ping = channel.unary_unary(
        '/bfkv.BfKvService/Ping',
        request_serializer=bfgateway__pb2.BfPingData.SerializeToString,
        response_deserializer=bfgateway__pb2.BfPingData.FromString,
        )
    self.PingStreamCS = channel.stream_stream(
        '/bfkv.BfKvService/PingStreamCS',
        request_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
        )
    self.PingStreamC = channel.stream_unary(
        '/bfkv.BfKvService/PingStreamC',
        request_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
        )
    self.PingStreamS = channel.unary_stream(
        '/bfkv.BfKvService/PingStreamS',
        request_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
        response_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
        )
    self.SetKv = channel.unary_unary(
        '/bfkv.BfKvService/SetKv',
        request_serializer=bfgateway__pb2.BfKvData.SerializeToString,
        response_deserializer=bfgateway__pb2.BfVoid.FromString,
        )
    self.GetKv = channel.unary_unary(
        '/bfkv.BfKvService/GetKv',
        request_serializer=bfgateway__pb2.BfKvData.SerializeToString,
        response_deserializer=bfgateway__pb2.BfKvData.FromString,
        )


class BfKvServiceServicer(object):
  """============================



  Kv服务

  """

  def Ping(self, request, context):
    """活跃检测=
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PingStreamCS(self, request_iterator, context):
    """stream测试=
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PingStreamC(self, request_iterator, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def PingStreamS(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetKv(self, request, context):
    """Kv服务=
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetKv(self, request, context):
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_BfKvServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=bfgateway__pb2.BfPingData.FromString,
          response_serializer=bfgateway__pb2.BfPingData.SerializeToString,
      ),
      'PingStreamCS': grpc.stream_stream_rpc_method_handler(
          servicer.PingStreamCS,
          request_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
          response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
      ),
      'PingStreamC': grpc.stream_unary_rpc_method_handler(
          servicer.PingStreamC,
          request_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
          response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
      ),
      'PingStreamS': grpc.unary_stream_rpc_method_handler(
          servicer.PingStreamS,
          request_deserializer=google_dot_protobuf_dot_any__pb2.Any.FromString,
          response_serializer=google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
      ),
      'SetKv': grpc.unary_unary_rpc_method_handler(
          servicer.SetKv,
          request_deserializer=bfgateway__pb2.BfKvData.FromString,
          response_serializer=bfgateway__pb2.BfVoid.SerializeToString,
      ),
      'GetKv': grpc.unary_unary_rpc_method_handler(
          servicer.GetKv,
          request_deserializer=bfgateway__pb2.BfKvData.FromString,
          response_serializer=bfgateway__pb2.BfKvData.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bfkv.BfKvService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))


class BetaBfKvServiceServicer(object):
  """============================



  Kv服务

  """
  def Ping(self, request, context):
    """活跃检测=
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def PingStreamCS(self, request_iterator, context):
    """stream测试=
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def PingStreamC(self, request_iterator, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def PingStreamS(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def SetKv(self, request, context):
    """Kv服务=
    """
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
  def GetKv(self, request, context):
    context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


class BetaBfKvServiceStub(object):
  """============================



  Kv服务

  """
  def Ping(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """活跃检测=
    """
    raise NotImplementedError()
  Ping.future = None
  def PingStreamCS(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
    """stream测试=
    """
    raise NotImplementedError()
  def PingStreamC(self, request_iterator, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  PingStreamC.future = None
  def PingStreamS(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  def SetKv(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    """Kv服务=
    """
    raise NotImplementedError()
  SetKv.future = None
  def GetKv(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
    raise NotImplementedError()
  GetKv.future = None


def beta_create_BfKvService_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
  request_deserializers = {
    ('bfkv.BfKvService', 'GetKv'): bfgateway__pb2.BfKvData.FromString,
    ('bfkv.BfKvService', 'Ping'): bfgateway__pb2.BfPingData.FromString,
    ('bfkv.BfKvService', 'PingStreamC'): google_dot_protobuf_dot_any__pb2.Any.FromString,
    ('bfkv.BfKvService', 'PingStreamCS'): google_dot_protobuf_dot_any__pb2.Any.FromString,
    ('bfkv.BfKvService', 'PingStreamS'): google_dot_protobuf_dot_any__pb2.Any.FromString,
    ('bfkv.BfKvService', 'SetKv'): bfgateway__pb2.BfKvData.FromString,
  }
  response_serializers = {
    ('bfkv.BfKvService', 'GetKv'): bfgateway__pb2.BfKvData.SerializeToString,
    ('bfkv.BfKvService', 'Ping'): bfgateway__pb2.BfPingData.SerializeToString,
    ('bfkv.BfKvService', 'PingStreamC'): google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
    ('bfkv.BfKvService', 'PingStreamCS'): google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
    ('bfkv.BfKvService', 'PingStreamS'): google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
    ('bfkv.BfKvService', 'SetKv'): bfgateway__pb2.BfVoid.SerializeToString,
  }
  method_implementations = {
    ('bfkv.BfKvService', 'GetKv'): face_utilities.unary_unary_inline(servicer.GetKv),
    ('bfkv.BfKvService', 'Ping'): face_utilities.unary_unary_inline(servicer.Ping),
    ('bfkv.BfKvService', 'PingStreamC'): face_utilities.stream_unary_inline(servicer.PingStreamC),
    ('bfkv.BfKvService', 'PingStreamCS'): face_utilities.stream_stream_inline(servicer.PingStreamCS),
    ('bfkv.BfKvService', 'PingStreamS'): face_utilities.unary_stream_inline(servicer.PingStreamS),
    ('bfkv.BfKvService', 'SetKv'): face_utilities.unary_unary_inline(servicer.SetKv),
  }
  server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
  return beta_implementations.server(method_implementations, options=server_options)


def beta_create_BfKvService_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
  request_serializers = {
    ('bfkv.BfKvService', 'GetKv'): bfgateway__pb2.BfKvData.SerializeToString,
    ('bfkv.BfKvService', 'Ping'): bfgateway__pb2.BfPingData.SerializeToString,
    ('bfkv.BfKvService', 'PingStreamC'): google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
    ('bfkv.BfKvService', 'PingStreamCS'): google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
    ('bfkv.BfKvService', 'PingStreamS'): google_dot_protobuf_dot_any__pb2.Any.SerializeToString,
    ('bfkv.BfKvService', 'SetKv'): bfgateway__pb2.BfKvData.SerializeToString,
  }
  response_deserializers = {
    ('bfkv.BfKvService', 'GetKv'): bfgateway__pb2.BfKvData.FromString,
    ('bfkv.BfKvService', 'Ping'): bfgateway__pb2.BfPingData.FromString,
    ('bfkv.BfKvService', 'PingStreamC'): google_dot_protobuf_dot_any__pb2.Any.FromString,
    ('bfkv.BfKvService', 'PingStreamCS'): google_dot_protobuf_dot_any__pb2.Any.FromString,
    ('bfkv.BfKvService', 'PingStreamS'): google_dot_protobuf_dot_any__pb2.Any.FromString,
    ('bfkv.BfKvService', 'SetKv'): bfgateway__pb2.BfVoid.FromString,
  }
  cardinalities = {
    'GetKv': cardinality.Cardinality.UNARY_UNARY,
    'Ping': cardinality.Cardinality.UNARY_UNARY,
    'PingStreamC': cardinality.Cardinality.STREAM_UNARY,
    'PingStreamCS': cardinality.Cardinality.STREAM_STREAM,
    'PingStreamS': cardinality.Cardinality.UNARY_STREAM,
    'SetKv': cardinality.Cardinality.UNARY_UNARY,
  }
  stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
  return beta_implementations.dynamic_stub(channel, 'bfkv.BfKvService', cardinalities, options=stub_options)
# @@protoc_insertion_point(module_scope)
